branches:
  only:
  - master
  - develop
  - /^[Rr]elease-.+/
  - /^[Ff]eature\/.+$/
  - /^[Hh]otfix\/.+$/
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
notifications:
  email: false
language: node_js
node_js:
- 9.2
install:
- yarn install
script:
- yarn run lint
- yarn run test
- yarn run build
